name: Deploy
on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      ACR_ADMIN_USERNAME: "funnyapp"
      ACR_LOGIN_SERVER_URL: "funnyapp.azurecr.io"
      ACR_ADMIN_PASSWORD: '${{ secrets.ACR_ADMIN_PASSWORD }}'
    if: github.repository != 'corndeladmin/DevOps-Unit-10-Workshop'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build \
            --target production \
            --tag ${{ env.ACR_LOGIN_SERVER_URL }}/monitoring_workshop/unit-10-order-processing-app:latest .

      - name: Login to ACR
        run: |
          echo ${{ env.ACR_ADMIN_PASSWORD }} | docker login -u ${{ env.ACR_ADMIN_USERNAME }} --password-stdin ${{ env.ACR_LOGIN_SERVER_URL }}

      - name: Push Docker image
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER_URL }}/monitoring_workshop/unit-10-order-processing-app:latest
          
